version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
      - blockchain
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: academia
      POSTGRES_PASSWORD: password
      POSTGRES_DB: academia
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  blockchain:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
volumes:
  db_data: